//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sweetshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeProduct
    {
        public int Id { get; set; }
        public int IdRecipes { get; set; }
        public int IdProducts { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
